server:
  port: 9090
spring:
  application:
    name: samplegateway
  cloud:
    kubernetes:
      enabled:  false
      discovery:
        enabled:  false    
appservice:
  discovery:
    host: host.docker.internal
    port: 9091
eureka:
    instance:
      preferIpAddress: true
      hostname: ${appservice.discovery.host}
    client:
      registerWithEureka: true
      fetchRegistry: true
      serviceUrl:
        defaultZone: http://${appservice.discovery.host}:${appservice.discovery.port}/eureka
management:
  endpoints:
    web:
      exposure:
        include: "*"
ribbon:
  eureka:
    enabled: true
zuul:
  routes:
    samplemvc: /emp/**